trigger:
  branches:
    include:
      - feature/ovas04-hu0-devops01-azurepipelines
  paths:
    include:
      - back/*
    exclude:
      - front/*


variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)' 

  # Container registry service connection established during pipeline creation
  dockerfilePath: '**/Dockerfile'
  buildTag: '$(Build.BuildId)'
  latestTag: 'latest'

stages:
  - stage: 'Build'
    displayName: 'Build Spring Boot App'
    jobs:
    - job: 'build'
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Cache@2
          inputs:      
            key: 'maven | "$(Agent.OS)" | **/pom.xml'
            restoreKeys: |
              maven | "$(Agent.OS)"
              maven
            path: $(MAVEN_CACHE_FOLDER)
          displayName: Cache Maven local repo
          
        - task: Maven@3
          inputs:
            mavenPomFile: "back/pom.xml"
            mavenOptions: "-Xmx3072m"
            javaHomeOption: "JDKVersion"
            jdkVersionOption: "1.11"
            jdkArchitectureOption: "x64"
            publishJUnitResults: true
            testResultsFiles: "**/surefire-reports/TEST-*.xml"
            goals: "clean"
            mavenAuthenticateFeed: true
            options: "-X -P azure_artifacts $(MAVEN_OPTS) --llr -Dmaven.test.skip=true"
          displayName: Build App
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub-ovas04'
            repository: 'ovas04/back-vivavintage'
            command: 'buildAndPush'
            Dockerfile: '$(dockerfilePath)'
            buildContext: '$(System.DefaultWorkingDirectory)/'
            tags: |
              $(buildTag)
              $(latestTag)

  - stage: 'Test'
    displayName: 'Test Spring Boot App'
    jobs:
    - job: 'test'
      pool:
        vmImage: ubuntu-latest
      steps:
        - task: Cache@2
          inputs:      
            key: 'maven | "$(Agent.OS)" | **/pom.xml'
            restoreKeys: |
              maven | "$(Agent.OS)"
              maven
            path: $(MAVEN_CACHE_FOLDER)
          displayName: Cache Maven local repo

        - task: Maven@3
          inputs:
            mavenPomFile: "back/pom.xml"
            mavenOptions: "-Xmx3072m"
            javaHomeOption: "JDKVersion"
            jdkVersionOption: "1.11"
            jdkArchitectureOption: "x64"
            publishJUnitResults: true
            testResultsFiles: "**/surefire-reports/TEST-*.xml"
            goals: "clean"
            mavenAuthenticateFeed: true
            options: "-X -P azure_artifacts $(MAVEN_OPTS)"
          displayName: Test App

  - stage: 'Release Docker Hub'
    displayName: 'Test Spring Boot App'
    jobs:
    - job: 'ReleaseDockerHub'
      pool:
        vmImage: ubuntu-latest
      steps:
       - task: Docker@2
         inputs:
           containerRegistry: 'dockerhub-ovas04'
           repository: 'ovas04/back-vivavintage'
           command: 'buildAndPush'
           Dockerfile: '**/Dockerfile'

