trigger:
  branches:
    include:
      - feature/ovas04-hu0-devops01-azurepipelines
  paths:
    include:
      - front/*
    exclude:
      - back/*

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)' 

  # Container registry service connection established during pipeline creation
  dockerfilePath: 'front/Dockerfile'
  buildTag: '$(Build.BuildId)'
  latestTag: 'latest'
  
pool:
  vmImage: ubuntu-latest
stages:
  - stage: 'Build'
    displayName: 'Build React App'
    jobs:
    - job: 'build'
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: "10.x"
          displayName: "Install Node.js"

        - script: npm install
          displayName: "Install NPM"
          
        - script: npm run dev
          displayName: "Build"

  - stage: 'Test'
    displayName: 'Test React App'
    jobs:
    - job: 'test'
      steps:
        - script: |
            curl -X GET http://localhost:3000 > response.txt
            if grep -q "E-commerce" response.txt; then
              echo "Data found in the response"
            else
              echo "Data not found in the response"
              exit 1
            fi
          failOnStderr: true
          workingDirectory: $(Build.SourcesDirectory)
          condition: and(succeeded()
          continueOnError: false
          target: host
          enabled: true
          env:
            TEST_ENVIRONMENT: staging
            TEST_SUITE: full
          name: "RunTests"
          retryCountOnTaskFailure: 1
          displayName: Validate with curl


  - stage: 'Release_Docker_Hub'
    displayName: 'Release into DockerHub'
    jobs:
    - job: 'releaseDockerHub'
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhubRepository'
            repository: 'ovas04/front-vivavintage'
            command: 'buildAndPush'
            Dockerfile: '$(dockerfilePath)'
            buildContext: '$(System.DefaultWorkingDirectory)/front/'
            tags: |
              $(buildTag)
              $(latestTag)
          displayName: Release Into DockerHub


