trigger:
  branches:
    include:
      - feature/ovas04-hu0-devops01-azurepipelines
  paths:
    include:
      - front/*
    exclude:
      - back/*

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  # Container registry service connection established during pipeline creation
  dockerfilePath: 'front/Dockerfile'
  buildTag: '$(Build.BuildId)'
  latestTag: 'latest'
  
pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Build'
    displayName: 'Build React App'
    jobs:
    - job: 'build'
      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "16.x"
        displayName: "Install Node.js"

      - script: npm install
        workingDirectory: $(Build.SourcesDirectory)/front/
        displayName: "Install NPM"

      - script:  npm run build
        workingDirectory: $(Build.SourcesDirectory)/front/
        displayName: "Build App"
        timeoutInMinutes: 1
        failOnStderr: false

  - stage: 'Test'
    displayName: 'Test React App'
    jobs:
    - job: 'test'
      steps:
      - script:  |
          npm run dev 
        workingDirectory: $(Build.SourcesDirectory)/front/
        timeoutInMinutes: 1
        retryCountOnTaskFailure: 0
        displayName: "Test App"

  - stage: 'Release_Docker_Hub'
    displayName: 'Release into DockerHub'
    jobs:
    - job: 'releaseDockerHub'
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhubRepository'
            repository: 'ovas04/front-vivavintage'
            command: 'buildAndPush'
            Dockerfile: '$(dockerfilePath)'
            buildContext: '$(System.DefaultWorkingDirectory)/front/'
            tags: |
              $(buildTag)
              $(latestTag)
          displayName: "Release Into DockerHub"
